### ISSUE TITLE
[Regression] Some sounds stopped looping after FileSystem commit

### ISSUE THREAD

**Issue by LAGonauta** [LAGonauta/MetaAudio#12]
For some reason some audio files stopped being detected as looping by libsndfile (maybe by other decoders also).
Example: plats/freightmove1.wav

**Comment by l0m-dev** [comment]
I also have trouble making a looping sound. Making loop points with wavosaur isn't working for me.

**Comment by LAGonauta** [comment]
@l0m-dev are you using version 0.0.9 or version 0.1.0? This regression was added in 0.1.0, are you also having problems with 0.0.9?

**Comment by LAGonauta** [comment]
Should be fixed on master, will do more testing before generating a new release.

**Comment by l0m-dev** [comment]
I was using wav files. I tried it on regular half life and it seems like I don't know how to make a looping sound in the first place. I thought adding looping points was enough.

**Comment by LAGonauta** [comment]
In theory one would just need to add cue points to the file 🤔

**Comment by l0m-dev** [comment]
Yeah. Maybe because of higher frequency it doesn't detect it as looping? 22kHz.

**Comment by LAGonauta** [comment]
Can you send me a sample file?

**Comment by l0m-dev** [comment]
Sure. https://vocaroo.com/i/s1yAqQek1IQO

**Comment by LAGonauta** [comment]
I opened the file in HxD and couldn't find any cue point (they come right after a `cue ` marker in a WAV file), maybe the software is not conforming to the standard, or not working?

**Comment by l0m-dev** [comment]
Well no matter what I try I cannot get it to make a cue point.

**Comment by LAGonauta** [comment]
Closing as it was fixed.

**Comment by LAGonauta** [comment]
Some sound files are still not being detected as looping, such as _ambience/warn3_. Reopening.

**Comment by LAGonauta** [comment]
Hopefully fixed now.
