### ISSUE TITLE
Sound of tank shells flying by stuck on loop

### ISSUE THREAD

**Issue by lazycrypt** [LAGonauta/MetaAudio#13]
So the recent release seems to have fixed some sound effects not playing however I'm just going through the Surface Tension, the tank section and occasionally when they fire the shell flying by SFX just seems to be stuck in loop even though the shell hit something. The SFX of the shell flying can be continuously heard around the point where it exploded.

**Comment by LAGonauta** [comment]
Yeah, that is a know bug. Sometimes the engine does not send the command to stop the sound properly. This happened even on A3D, but for some reason not so much with Miles.
There is even a door that can be opened with a wheel that this always happened with A3D.

However, if it is happening more often with the current version that is a bug that needs to be fixed. Do you know if this is happening more often?

**Comment by lazycrypt** [comment]
I'll keep an ear out but I've only noticed it happening with the tanks so it could just be an old bug.
