### ISSUE TITLE
Any chance this mod can be made to work with a non-steam version of the game?

### ISSUE THREAD

**Issue by ank81** [LAGonauta/MetaAudio#15]
Like 1.1.2.0? I tried running it, but MetaAudio refuses to start, I don't remember the message it throws up, but it's using that standard Windows 7 frame, as when you plug in a usb drive, not the dll error one. In fact I think it's only offering to close the application.

Thank you

**Comment by LAGonauta** [comment]
Is that the WON version with multiplayer patches (WON2)? Sadly no as MetaHook doesn't support it as far as I know.

**Comment by ank81** [comment]
Yes, I believe so. It's the Steamless Project version [https://www.moddb.com/downloads/half-life-update-1112-patch](url). A pity it won't work though.
