### ISSUE TITLE
Some DSP presets aren't too vivid

### ISSUE THREAD

**Issue by HalfWayLambda** [LAGonauta/MetaAudio#19]
First of all, thank you for making this mod, it's really amazing to see that you can have amazing audio in all GoldSrc games and mods in 2020 without the need of old WON versions and specific sound card hardware to get it to work!

But after testing it a little bit I realized that some dsp presets in Half-Life with this mod don't sound so "vivid" as the corresponding ones sound like with the Miles Sound System. An example of this are the chamber presets. In Miles it did sound fake (just like almost all of the presets) but it was very intensive and it gave you a really good feel about how big the area was. But with this mod it sounds like a very, very smaller room in comparison.
For instance, the chamber large preset in Miles sounds like a huge chamber that was like, 500 metres across because the sound echoed for a lot of seconds. But with this mod the echo has already died off in just 1 second, which is really weak compared to Miles.

So my idea was to change some of these and make them more intense. Specifically, the chamber, metal, and concrete presets are among the weakest compared to their Miles counterparts. I don't know how much you can do about that however, so if it's not possible just let me know! I think being able to customize their intensity would also be a really cool idea, if possible to implement that is.
(Also random sidenote: The "weirdo" presets also sound nothing like the ones in Miles. The Weirdo 2 for instance sounded like angry bees when there was a loud sound in Miles but in this mod it sounds like there's an echo that comes back to you after a few seconds and never dies off, which is definitely not the same thing if you get what I mean.)

**Comment by HalfWayLambda** [comment]
Ah alright, i'm glad to see you're still working on this mod/plugin and it definitely deserves more attention! I'm looking forward to the update that let's you customize the parameters in the near future! Good luck!

**Comment by LAGonauta** [comment]
You will be able to customize reverb presets after #20 is merged :)

**Comment by LAGonauta** [comment]
Merged #20
