### ISSUE TITLE
Egon sound is looped after firing stopped

### ISSUE THREAD

**Issue by BlackShadow** [LAGonauta/MetaAudio#24]
Egon sound still continues playing after firing stopped. This happens randomly. 

Meta Audio Version: 92b7efb1ffebb94e3d20ed89f6dd72b50264b16f
OpenAL Device: OpenAL Soft on Headphones (Razer Nari Ultimate - Game)
OpenAL Version: 1.1

**Comment by LAGonauta** [comment]
Can you test this one?
[MetaAudio.Alure.zip](https://github.com/LAGonauta/MetaAudio/files/5612706/MetaAudio.Alure.zip)

It is current master.

**Comment by BlackShadow** [comment]
Great work, it seems fixed!
