### ISSUE TITLE
Game is offset when runnning under 1440p fullscreen

### ISSUE THREAD

**Issue by CaptainCosmotic** [LAGonauta/MetaAudio#33]
When I run Halflife in 1440p via Metahook the screen is zoomed in and shifted so i cant see the menu. ingame its shifted too. Vanilla Half-Life does not have this issue.
I can work around it with -windowed -noborder but it's not fun to play like this because sometimes if I make alot of inputs the borderless window moves a bit.
Running on Windows 10 
with the Releasecanidate 1
![hl](https://user-images.githubusercontent.com/57239116/120047071-ebecac00-c013-11eb-9099-75152bbabc16.jpg)

**Comment by CaptainCosmotic** [comment]
Okay sorry for the issue i solved it by setting my "Change the size of text, apps, and other items" in my display settings to %100

**Comment by MrSwedish** [comment]
close it then
