### ISSUE TITLE
Can't play FLAC files 

### ISSUE THREAD

**Issue by Oztrus** [LAGonauta/MetaAudio#34]
I replaced the music in valve/media from MP3 to FLAC, and whenever I launch the game it won't play the FLAC files.
am I missing something? cause the comment about Alure2 tells me that I would have to compile Alure2 with FLAC to get it working.

**Comment by LAGonauta** [comment]
MetaAudio is not used to play the music, only the sound effects.
This is why it doesn't work, but it would be great if it did :)
