### ISSUE TITLE
MetaHook.exe Runs But the MetaAudio plugin is not running

### ISSUE THREAD

**Issue by Just-Kamil** [LAGonauta/MetaAudio#44]
![image](https://user-images.githubusercontent.com/56370060/163881912-e2ab8d9a-c3d1-493e-80b7-14116fbb683f.png)
MetaHook Appears to be running however the plugin isn't

![image](https://user-images.githubusercontent.com/56370060/163882012-2d23f9fb-926d-4013-8e31-9b67e70f7646.png)
Screenshot in-game

I'm not entirely sure what isn't working, I tried following #10  but that changed nothing even going as far as replacing the OpenAL in sysWOW64 and system32 with the 32bit versions I tried downloading the debug build but it sent me to a ```File Not Found``` page

**Comment by IDDQD1337** [comment]
Just put MetaHook in game folder

**Comment by LAGonauta** [comment]
@Just-Kamil 
Were you able to solve your problem? If not, we can move this discussion to https://github.com/LAGonauta/MetaAudio/discussions
