### ISSUE TITLE
Resolution Issue

### ISSUE THREAD

**Issue by SystemShocker287** [LAGonauta/MetaAudio#47]
Good Evening. Im trying to use MetaAudio with Half-Life,but everytime I try to run it,this happens
![image](https://user-images.githubusercontent.com/111618404/192120103-8cdf9cf7-8b63-422a-8c9d-f5a798c9f62e.png)

**Comment by BlackShadow** [comment]
Change Desktop Scaling (DPI) to %100

**Comment by SystemShocker287** [comment]
How?

**Comment by BlackShadow** [comment]
> How?

I assume you have Win10:

Right click to desktop, choose Display Settings, You'll see Scale and Layout there, under that there's an option says 
"Change the size of text, apps, and other items" change it to %100

**Comment by LAGonauta** [comment]
@SystemShocker287 
Hopefully you were able to fix the resolution issue, if you have further problems about this you can open a discussion on https://github.com/LAGonauta/MetaAudio/discussions
