### ISSUE TITLE
Why would metaaudio cause a ban?

### ISSUE THREAD

**Issue by michaeljhkim** [LAGonauta/MetaAudio#55]
Hi! So I really want to play this mod, but I am scared of getting a ban, and I would just like to ask how I could possibly get a ban from this mod if I played this on a server?

**Comment by BlackShadow** [comment]
Because you're hooking external DLLs to the game and that what cheats do, which is might tamper VAC. Better safe than sorry. You can use Non-Steam if you'd like to use it.
