### ISSUE TITLE
Linux port?

### ISSUE THREAD

**Issue by michaeljhkim** [LAGonauta/MetaAudio#56]
There does not seem to be a way to use this on linux yet. But will there be a linux port?

**Comment by LAGonauta** [comment]
I wish, but unfortunately I am not knowledgeable enough to be able to do so.

**Comment by fred0r** [comment]
has there been any progress on your knowledge regarding this topic?
,)

**Comment by Glitch31415** [comment]
+1 for Linux port, please!
