### ISSUE TITLE
Request: Possible to add support for the latest Steam Audio API?

### ISSUE THREAD

**Issue by RavenMacDaddy** [LAGonauta/MetaAudio#61]
I checked the releases for the SteamAudio API, and seemingly only the **phonon.dll** for v2.0 works (to be fair, that's what's being referred to).

Is it possible, now with updates for both HL25 and the utilization of MetaHookSv code, to add support for v4 and later revisions?

**Comment by LAGonauta** [comment]
Yes, this is actually being worked on. However, the updated engine is not exporting the map data for some reason so it just crashes. A bug that Valve needs to fix, or I will need to load the BSP manually.

**Comment by RavenMacDaddy** [comment]
I was just about to report that as well; v2.0 crashing with HL25 etc. — that explains it.

**Comment by LAGonauta** [comment]
The SteamAudio crash should have been fixed on master

**Comment by RavenMacDaddy** [comment]
I can confirm that the latest v2.0 release, Beta 20, does not crash and the CVAR al_occluder shows up in the console.

Have you gotten any release of v4 to work on your end, or is that still down the line?

**Comment by RavenMacDaddy** [comment]
The latest versions of Steam Audio are now working — closing.
