### ISSUE TITLE
X-Fi Hardware Acceleration Crashes Half-Life when Loading Between Levels

### ISSUE THREAD

**Issue by Daedalus0155** [LAGonauta/MetaAudio#67]
Steps to Reproduce:

1. Omit OpenAL32.dll
2. Add MetaHook.exe to Creative Alchemy (this official software exists so X-Fi can provide EAX support)
3. Start OpenAL Half-Life
4. Start Training Course
5. Progress until new level must be loaded
6. Game crashes

Hardware Type: Creative X-FI Surround (USB), Model Number: SB1090

**Comment by LAGonauta** [comment]
Unfortunately only some PCI and PCI-E X-Fi cards support hardware acceleration, and Creative Alchemy shouldn't be used with the plugin as MetaAudio doesn't use DirectSound.
I would say at best it has no effect, at worst the software OpenAL driver gets confused.

You are better off just using OpenAL Soft, while I do want to fix crashes with Creative's software OpenAL driver (sens_oal.dll) I don't have a card that uses that driver to test
