### ISSUE TITLE
Reverb Volume/X-fi Titanium CMSS

### ISSUE THREAD

**Issue by Mutch0199** [LAGonauta/MetaAudio#68]
Hello, and thank you for the mod. I recently installed an x-fi card on my PC and noticed that the reverb for hl1 is far louder on OpenALsoft than it is on a native OpenAL rendering device. I tried adjusting the OpenALsoft boost parameter in the alsoft.ini in both half life and %appdata% but to no avail, and was wondering if there was something I was missing. Additionally, I was wondering how Hrtf is done without the OpenAL32 present via hardware acceleration. Is it still using OpenALsoft's HRTF or will I need to enable something like CMSS-3D? Sorry for multiple questions but I am still learning how all of this works. Thank you.

**Comment by LAGonauta** [comment]
OpenAL Soft's reverb and X-Fi's reverb do not match perfectly for some reason, this is most likely the reason you are hearing difference. I _think_ newer versions are supposed to be more similar, but I am not sure.
> will I need to enable something like CMSS-3D?

Yes, you do need to enable CMSS-3D. Set the X-Fi to game mode, enable headphones mode, enable CMSS-3D, and enable MacroFX and Elevation Filter for the full effect.
