### ISSUE TITLE
Questions about the installation

### ISSUE THREAD

**Issue by NotTheMindProbe** [LAGonauta/MetaAudio#71]
### Discussed in https://github.com/LAGonauta/MetaAudio/discussions/70

<div type='discussions-op-text'>

<sup>Originally posted by **NotTheMindProbe** March 23, 2024</sup>
First, regarding manual installation - where's the "metahook" folder? I can't find any folder with that name in the repo, anywhere.
Second, regarding compilation and quick install - I tried compiling but the install bat for the title I want (HL Opposing Force) still says it can't find the compiled binaries. Plus running _build-initdeps.bat_ took just a few seconds and it only downloaded a single file</div>

**Comment by lespaul64** [comment]
Let say for Steam Counter-Strike 1.6

```
Half-Life
	--> MetaHook.exe
	--> openal32.dll
	--> sndfile.dll
	--> phonon.dll
	
	--> cstrike
		--> metahook
			--> configs
				--> plugins.lst
			--> plugins
				--> MetaAudio.dll
```

Hope this will help you.
