### ISSUE TITLE
Constantly gettting "MH_LoadPlugin" issue

### ISSUE THREAD

**Issue by thedrakeraider** [LAGonauta/MetaAudio#74]
MetaHooks is loading just fine, but I'm constantly getting error 126: The specified module could not be found when trying to load the game with MetaAudio in the plugins.lst. The plugin is absolutely installed correctly (matching the file tree,) unless there's something I'm missing that's not in the guide here:
https://pastebin.com/L5BTxMVW

Perhaps it's an openal bug, but I've deleted and restored all my OpenAL dlls in all locations (System32, SysWow64, and the HL main folder) in every combination and I've gotten no progress.

**Comment by Dundunthegreatest** [comment]
the pre-release metaaudio.dll just wont get detected for some reason, but the latest version will

**Comment by thedrakeraider** [comment]
If it's the 2020 one you mean, that has an entirely different crash. something about S_Findname 9920 and !m_bMounted line 84. Is there another one I'm missing?

**Comment by LAGonauta** [comment]
You can download latest [master](https://github.com/LAGonauta/MetaAudio/releases/tag/master) pre-release (currently MetaAudio-312) and use sndfile.dll from there, it is inside externals and need to be copied to the same folder of **metahook.exe**. If you have and old **libsndfile.dll** in the same folder, remove them.
